# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfc126ad87291dc90a5010b631335499a0cad26c144c5d301d8ec6392b8614fa41a61030a89131d3bc0a3bad6ce83c906eb9b2ffc4cb912ba816eb908525d1d2

test:
  secret_key_base: c91b8fcd7204afe8cbb03bea38df41953e455ffbc7ffd299d9fa3d9611c937083b50382cab111ff35b92752bffc4d7b7a675fa07953972b302ac387a94e5d232

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
