# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b3b04d8fc6f93728360d136b6984a33556a8238dc74c3d983b0091acf1f87f64cfa3e8c5a2cd0296f33b5746da0fd686713cef317fa776db4f64054d65c2f64

test:
  secret_key_base: 45a6e74c987b09c442b662df02fcd050087422577759dc119348a9a520689e432a650fdeeea63f0bbf0a01e8fcdb834f5056015deae6e73b080ead733d3971fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
